[tool.poetry]
name = "color_blame"
version = "0.1.0"
description = ""
authors = ["Kevin Yokley <kyokley2@gmail.com>"]

[tool.poetry.dependencies]
python = "^3.8"
colorclass = "^2.2.0"

[tool.poetry.dev-dependencies]
pytest = "^6.0.0"
pytest-mock = "^3.2.0"
bpython = "^0.19"
pdbpp = "^0.10.2"

[build-system]
requires = ["poetry>=0.12"]
build-backend = "poetry.masonry.api"
